### ISSUE TITLE
[Itinary Actor] seems to trigger only the first action when sequence use TweenActors

### ISSUE THREAD

**Issue by Manukineko** [dicksonlaw583/GMTwerk2#1]
I set up an Itinary in the create event, with two Actions.
Action are simple TweenActor. Here is the code :
```gml
slotSlideIn = Itinerary(200,[
	[200, function(){Tween(InstanceVar("bgx").set(56), 0, 500, ["type", te_cubic_out]); }],
	[100, function(){Tween(InstanceVar("mgx").set(56), 0, 500, ["type", te_cubic_out]); }]
],[false] );
```
Then I draw two sprite in the Draw Event :
```gml
draw_sprite(BG,0,x+bgx,y);
draw_sprite(Mugshot,0,x+mgx,y);
```
The result :
![ItinaryBug](https://user-images.githubusercontent.com/43104858/113472436-2d425e80-949e-11eb-98aa-9484c6ce8303.png)

The BG sprite (yellow part) perform the expected tween, but the Mugshot stoped a the x value set in the set method (56).
When I log the value, it shows all the modified value of bgx, but logging mgx return only the value set in the create event.

It seems the ItinaryActor doesn't compute the seconde Tween action.

**Comment by dicksonlaw583** [comment]
Thank you for reporting this bug. I have included your reproduction to the test suite and added the corresponding fix.
 
Due to the criticality of this bug and another reported crash on GMS 2.3.2, I will be releasing a patch release later today.

**Comment by Manukineko** [comment]
Wonderful, like GMTwerks by the way.
I have another bug to report, but I may wait the patch release first because it could be related to this one.

**Comment by dicksonlaw583** [comment]
The patch release is actually available now at [the Releases page](https://github.com/dicksonlaw583/GMTwerk2/releases/tag/v2.0.2). YoYo Marketplace is still processing my submission, so the version there is still the old one as of now.

**Comment by Manukineko** [comment]
I did the update and it works now and the other bug is gone as well (it was related).

Time for another "bug" I found, but it could be related to how Gamemaker execute its events. 

**Edit :** I fill a bug report #3
