### ISSUE TITLE
Crash with multi-value using StructVec

### ISSUE THREAD

**Issue by Manukineko** [dicksonlaw583/GMTwerk2#4]
Hello,

I'm not sur if this is a bug or me who set it up the wrong way.

I am tweening two struct variable values:
```gml
//Create
item1 = {
            scale:2,
            xscale:1,
            yscale:1
}
Tween(StructVec(["xscale","yscale"],item1), StructVec(["scale","scale"],item1),400, [
	"type",te_cubic_out,
	"blend", tb_vector
]);
```
But, it seems the tb_vector function is feeded the whole target struct.
![image](https://user-images.githubusercontent.com/43104858/143847299-2c8f661a-1c56-4088-b207-505a726d4454.png)

Am I doing something wrong ?

**Comment by dicksonlaw583** [comment]
`Tween` takes one selector and one target value, you gave it two selectors. The actor that takes two selectors is `Track`.

Either you do this for a one-time transition:
```
Tween(StructVec(["xscale", "yscale"], item1), [item1.scale, item1.scale], 400, [
    "type", te_cubic_out,
    "blend", tb_vector,
]);
```

Or this to keep `xscale` and `yscale` following `scale` on an ongoing basis:
```
Track(StructVec(["xscale", "yscale"], item1), StructVec(["scale", "scale"], item1), 400, [
    "type", te_cubic_out,
    "blend", tb_vector,
]);
```

**Comment by Manukineko** [comment]
Got it. Thanks.

I was wrongly assuming, based on the exemple shown for multiple values, that Tween would work the same way with StructVec than it works with InstanceVec.

Thanks again, GMTwerk is a lot of fun to use.

**Comment by dicksonlaw583** [comment]
You are welcome. I will close this issue as it appears to be resolved. Feel free to let me know when you have other questions about GMTwerk 2.
